#!/usr/bin/env python3
"""Profile-first speech wrapper around a compatible downstream speech CLI."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import subprocess
import sys
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

try:
    import yaml  # type: ignore
except Exception:  # pragma: no cover
    yaml = None

ALLOWED_VOICES = {
    "alloy",
    "ash",
    "ballad",
    "cedar",
    "coral",
    "echo",
    "fable",
    "marin",
    "nova",
    "onyx",
    "sage",
    "shimmer",
    "verse",
}

ALLOWED_FORMATS = {"mp3", "wav", "opus", "aac", "flac"}
PROFILE_ID_RE = re.compile(r"^[a-z0-9-]+$")
MAX_INPUT_CHARS = 4096
DEFAULT_DISCLOSURE = "This audio was generated by AI text-to-speech."
DEFAULT_PROFILES_FILE = "config/speech/profiles.yaml"
CONFIG_VERSION = "1"
BASELINE_DEFAULTS = {
    "model": "gpt-4o-mini-tts-2025-12-15",
    "voice": "cedar",
    "speed": 1.0,
    "response_format": "mp3",
    "instructions": "",
}

REQUIRED_MANIFEST_KEYS = [
    "timestamp",
    "input_source",
    "profile_id",
    "effective_voice",
    "effective_instructions",
    "effective_speed",
    "summarize_mode",
    "target_chars",
    "playback_backend",
    "playback_result",
    "backend_mode",
    "disclosure",
    "audio_output_path",
    "text_sha256",
]


class WrapperError(Exception):
    """User-facing wrapper error."""


@dataclass
class ProfileSet:
    default_profile: str | None
    profiles: dict[str, dict[str, Any]]


@dataclass
class PlaybackSummary:
    backend: str
    result: str
    attempted: int
    succeeded: int
    failed: int
    errors: list[str]
    exit_code: int


@dataclass
class RuntimeConfig:
    default_profiles_file: str = DEFAULT_PROFILES_FILE
    default_disclosure: str = DEFAULT_DISCLOSURE
    local_output_dir: str = "output/speech"
    local_playback_backend: str = "none"
    local_autoplay_generated_audio: bool = False


def _sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _read_text(args: argparse.Namespace) -> tuple[str, str]:
    if args.text is not None:
        text = args.text
        source = "inline"
    else:
        path = Path(args.text_file)
        if not path.exists():
            raise WrapperError(f"Text file not found: {path}")
        text = path.read_text(encoding="utf-8")
        source = str(path)

    if len(text) > MAX_INPUT_CHARS:
        raise WrapperError(
            f"Input text length {len(text)} exceeds {MAX_INPUT_CHARS}. "
            "M1 policy is fail-fast; split/chunk input before running."
        )
    return text, source


def _parse_profiles_file(path: Path) -> dict[str, Any]:
    raw = path.read_text(encoding="utf-8")
    if path.suffix.lower() == ".json":
        try:
            loaded = json.loads(raw)
        except json.JSONDecodeError as exc:
            raise WrapperError(f"Invalid JSON profiles file: {exc}") from exc
        if not isinstance(loaded, dict):
            raise WrapperError("Profiles file must parse as a top-level object.")
        return loaded
    if yaml is None:
        raise WrapperError("PyYAML not installed; YAML profile files are unavailable.")
    try:
        loaded = yaml.safe_load(raw)
    except Exception as exc:
        raise WrapperError(f"Invalid YAML profiles file: {exc}") from exc
    if not isinstance(loaded, dict):
        raise WrapperError("Profiles file must parse as a top-level object.")
    return loaded


def _load_yaml_object(path: Path, *, kind: str) -> dict[str, Any]:
    if yaml is None:
        raise WrapperError(f"PyYAML not installed; {kind} files are unavailable.")
    try:
        loaded = yaml.safe_load(path.read_text(encoding="utf-8"))
    except Exception as exc:
        raise WrapperError(f"Invalid YAML {kind} file: {exc}") from exc
    if loaded is None:
        return {}
    if not isinstance(loaded, dict):
        raise WrapperError(f"{kind.capitalize()} file must parse as a top-level object.")
    return loaded


def _validate_runtime_config_value(raw: dict[str, Any], key: str, expected_type: type, *, allow_none: bool = False) -> Any:
    value = raw.get(key)
    if value is None and allow_none:
        return None
    if value is None:
        return None
    if not isinstance(value, expected_type):
        raise WrapperError(f"Customization setting '{key}' must be of type {expected_type.__name__}")
    return value


def load_runtime_config() -> RuntimeConfig:
    paths = [
        Path("config/customization.template.yaml"),
        Path("config/customization.yaml"),
    ]

    merged = RuntimeConfig()
    found_any = False

    for path in paths:
        if not path.exists():
            continue
        found_any = True
        raw = _load_yaml_object(path, kind="customization")
        version = raw.get("version")
        if version != CONFIG_VERSION:
            raise WrapperError(f"Unsupported customization schema version in {path}: {version!r}. Expected '{CONFIG_VERSION}'.")

        workflow = raw.get("workflow", {})
        if workflow is None:
            workflow = {}
        if not isinstance(workflow, dict):
            raise WrapperError(f"Customization file {path} must contain a top-level 'workflow' object")

        local_cli = workflow.get("localCli", {})
        if local_cli is None:
            local_cli = {}
        if not isinstance(local_cli, dict):
            raise WrapperError(f"Customization file {path} must contain 'workflow.localCli' as an object")

        default_profiles_file = _validate_runtime_config_value(workflow, "defaultProfilesFile", str)
        default_disclosure = _validate_runtime_config_value(workflow, "defaultDisclosure", str)
        local_output_dir = _validate_runtime_config_value(local_cli, "defaultOutputDir", str)
        local_playback_backend = _validate_runtime_config_value(local_cli, "defaultPlaybackBackend", str)
        autoplay_generated_audio = _validate_runtime_config_value(local_cli, "autoplayGeneratedAudio", bool)

        if local_playback_backend is not None and local_playback_backend not in ("none", "open", "afplay"):
            raise WrapperError(
                "Customization setting 'localCli.defaultPlaybackBackend' must be one of: none, open, afplay"
            )

        if default_profiles_file is not None:
            merged.default_profiles_file = default_profiles_file
        if default_disclosure is not None:
            merged.default_disclosure = default_disclosure
        if local_output_dir is not None:
            merged.local_output_dir = local_output_dir
        if local_playback_backend is not None:
            merged.local_playback_backend = local_playback_backend
        if autoplay_generated_audio is not None:
            merged.local_autoplay_generated_audio = autoplay_generated_audio

    if not found_any:
        return RuntimeConfig()
    return merged


def _validate_profile_item(item: dict[str, Any], index: int) -> None:
    required = {"id", "voice", "instructions", "speed", "response_format"}
    missing = sorted(required - set(item.keys()))
    if missing:
        raise WrapperError(f"Profile #{index} missing required fields: {', '.join(missing)}")

    profile_id = item["id"]
    if not isinstance(profile_id, str) or not PROFILE_ID_RE.match(profile_id):
        raise WrapperError(f"Profile #{index} has invalid id: {profile_id!r}")

    voice = item["voice"]
    if voice not in ALLOWED_VOICES:
        raise WrapperError(f"Profile '{profile_id}' has unsupported voice: {voice}")

    fmt = item["response_format"]
    if fmt not in ALLOWED_FORMATS:
        raise WrapperError(f"Profile '{profile_id}' has unsupported response_format: {fmt}")

    instructions = item["instructions"]
    if not isinstance(instructions, str) or instructions.strip() == "":
        raise WrapperError(f"Profile '{profile_id}' requires non-empty instructions")

    speed = item["speed"]
    if not isinstance(speed, (float, int)):
        raise WrapperError(f"Profile '{profile_id}' speed must be numeric")
    speed_val = float(speed)
    if speed_val < 0.25 or speed_val > 4.0:
        raise WrapperError(f"Profile '{profile_id}' speed out of range [0.25, 4.0]: {speed}")


def load_profiles(path: Path) -> ProfileSet:
    if not path.exists():
        raise WrapperError(f"Profiles file not found: {path}")

    data = _parse_profiles_file(path)
    version = data.get("version")
    if version != "1":
        raise WrapperError(f"Unsupported profile schema version: {version!r}. Expected '1'.")

    raw_profiles = data.get("profiles")
    if not isinstance(raw_profiles, list) or len(raw_profiles) == 0:
        raise WrapperError("Profiles file must include a non-empty 'profiles' array")

    seen: set[str] = set()
    profiles: dict[str, dict[str, Any]] = {}
    for i, item in enumerate(raw_profiles, start=1):
        if not isinstance(item, dict):
            raise WrapperError(f"Profile #{i} must be an object")
        _validate_profile_item(item, i)
        profile_id = item["id"]
        if profile_id in seen:
            raise WrapperError(f"Duplicate profile id: {profile_id}")
        seen.add(profile_id)
        profiles[profile_id] = {
            "id": profile_id,
            "voice": item["voice"],
            "instructions": item["instructions"],
            "speed": float(item["speed"]),
            "response_format": item["response_format"],
            "description": item.get("description"),
            "disclosure": item.get("disclosure"),
            "tags": item.get("tags", []),
        }

    default_profile = data.get("default_profile")
    if default_profile is not None and default_profile not in profiles:
        raise WrapperError(
            f"default_profile '{default_profile}' not found in profiles: "
            f"{', '.join(sorted(profiles.keys()))}"
        )

    return ProfileSet(default_profile=default_profile, profiles=profiles)


def resolve_profile_set(args: argparse.Namespace, runtime_config: RuntimeConfig | None = None) -> ProfileSet | None:
    candidates: list[Path] = []
    if args.profiles_file:
        candidates.append(Path(args.profiles_file))
    else:
        default_profiles_file = runtime_config.default_profiles_file if runtime_config is not None else DEFAULT_PROFILES_FILE
        default_path = Path(default_profiles_file)
        if default_path.exists():
            candidates.append(default_path)

    if not candidates:
        if args.profile:
            raise WrapperError("--profile was provided but no profiles file was found.")
        return None

    return load_profiles(candidates[0])


def resolve_effective_config(
    args: argparse.Namespace, profile_set: ProfileSet | None, runtime_config: RuntimeConfig | None = None
) -> tuple[dict[str, Any], str | None, str | None, str]:
    profile_id: str | None = None
    profile_values: dict[str, Any] = {}
    profile_source: str | None = None

    if profile_set is not None:
        if args.profile:
            if args.profile not in profile_set.profiles:
                known = ", ".join(sorted(profile_set.profiles.keys()))
                raise WrapperError(f"Unknown profile '{args.profile}'. Known profiles: {known}")
            profile_id = args.profile
        elif profile_set.default_profile is not None:
            profile_id = profile_set.default_profile

        if profile_id is not None:
            profile_values = dict(profile_set.profiles[profile_id])
            profile_source = "file"
    # precedence: explicit flags > selected profile > baseline defaults
    effective = dict(BASELINE_DEFAULTS)
    for key in ("voice", "instructions", "speed", "response_format"):
        if key in profile_values and profile_values[key] is not None:
            effective[key] = profile_values[key]

    if args.voice is not None:
        effective["voice"] = args.voice
    if args.instructions is not None:
        effective["instructions"] = args.instructions
    if args.speed is not None:
        effective["speed"] = float(args.speed)
    if args.format is not None:
        effective["response_format"] = args.format
    if args.model is not None:
        effective["model"] = args.model

    if effective["voice"] not in ALLOWED_VOICES:
        raise WrapperError(f"Unsupported voice: {effective['voice']}")
    if effective["response_format"] not in ALLOWED_FORMATS:
        raise WrapperError(f"Unsupported format: {effective['response_format']}")
    speed = float(effective["speed"])
    if speed < 0.25 or speed > 4.0:
        raise WrapperError(f"Speed out of range [0.25, 4.0]: {speed}")
    disclosure = profile_values.get("disclosure") if profile_values else None
    if disclosure is None or str(disclosure).strip() == "":
        disclosure = runtime_config.default_disclosure if runtime_config is not None else DEFAULT_DISCLOSURE

    return effective, profile_id, profile_source, str(disclosure)


def resolve_output_path(args: argparse.Namespace, response_format: str, runtime_config: RuntimeConfig | None = None) -> Path:
    if args.out:
        out = Path(args.out)
        if out.suffix == "":
            out = out.with_suffix(f".{response_format}")
        return out

    ts = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    output_dir = runtime_config.local_output_dir if runtime_config is not None else "output/speech"
    return Path(output_dir) / f"speech-{ts}.{response_format}"


def build_tts_command(args: argparse.Namespace, text: str, effective: dict[str, Any], out_path: Path) -> list[str]:
    return [
        args.python_bin,
        args.tts_cli_path,
        "speak",
        "--input",
        text,
        "--voice",
        str(effective["voice"]),
        "--instructions",
        str(effective["instructions"]),
        "--speed",
        str(effective["speed"]),
        "--response-format",
        str(effective["response_format"]),
        "--model",
        str(effective["model"]),
        "--out",
        str(out_path),
    ]


def load_queue_file(path: Path) -> list[Path]:
    if not path.exists():
        raise WrapperError(f"Queue file not found: {path}")
    items: list[Path] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        candidate = line.strip()
        if not candidate or candidate.startswith("#"):
            continue
        items.append(Path(candidate))
    return items


def resolve_playback_queue(args: argparse.Namespace, out_path: Path, autoplay: bool | None = None) -> list[Path]:
    queue: list[Path] = []
    effective_autoplay = args.autoplay if autoplay is None else autoplay
    if effective_autoplay:
        queue.append(out_path)
    if args.queue_file:
        queue.extend(load_queue_file(Path(args.queue_file)))
    return queue


def _run_playback_command(backend: str, file_path: Path) -> list[str]:
    if backend == "open":
        return ["open", str(file_path)]
    if backend == "afplay":
        return ["afplay", str(file_path)]
    raise WrapperError(f"Unsupported playback backend: {backend}")


def execute_playback(
    *,
    backend: str,
    queue: list[Path],
    repeat: int,
    stop_on_error: bool,
    dry_run: bool,
) -> PlaybackSummary:
    if backend == "none":
        return PlaybackSummary(
            backend=backend,
            result="skipped",
            attempted=0,
            succeeded=0,
            failed=0,
            errors=[],
            exit_code=0,
        )
    if not queue:
        return PlaybackSummary(
            backend=backend,
            result="skipped",
            attempted=0,
            succeeded=0,
            failed=0,
            errors=[],
            exit_code=0,
        )
    if repeat < 1:
        raise WrapperError(f"--repeat must be >= 1 (received {repeat})")
    if dry_run:
        attempted = len(queue) * repeat
        return PlaybackSummary(
            backend=backend,
            result="dry_run",
            attempted=attempted,
            succeeded=0,
            failed=0,
            errors=[],
            exit_code=0,
        )

    attempted = 0
    succeeded = 0
    failed = 0
    errors: list[str] = []

    for file_path in queue:
        for _ in range(repeat):
            attempted += 1
            if not file_path.exists():
                failed += 1
                errors.append(f"File not found for playback: {file_path}")
                if stop_on_error:
                    return PlaybackSummary(
                        backend=backend,
                        result="failed",
                        attempted=attempted,
                        succeeded=succeeded,
                        failed=failed,
                        errors=errors,
                        exit_code=3,
                    )
                continue
            cmd = _run_playback_command(backend, file_path)
            try:
                subprocess.run(cmd, check=True)
                succeeded += 1
            except subprocess.CalledProcessError as exc:
                failed += 1
                errors.append(f"{backend} failed for {file_path} with exit code {exc.returncode}")
                if stop_on_error:
                    return PlaybackSummary(
                        backend=backend,
                        result="failed",
                        attempted=attempted,
                        succeeded=succeeded,
                        failed=failed,
                        errors=errors,
                        exit_code=3,
                    )

    result = "played" if failed == 0 else "partial"
    exit_code = 0 if failed == 0 else 3
    return PlaybackSummary(
        backend=backend,
        result=result,
        attempted=attempted,
        succeeded=succeeded,
        failed=failed,
        errors=errors,
        exit_code=exit_code,
    )


def write_manifest(out_path: Path, payload: dict[str, Any]) -> Path:
    missing = [k for k in REQUIRED_MANIFEST_KEYS if k not in payload]
    if missing:
        raise WrapperError(f"Cannot write manifest; missing keys: {', '.join(missing)}")

    manifest_path = out_path.with_suffix(out_path.suffix + ".manifest.json")
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest_path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return manifest_path


def parse_args(argv: list[str]) -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Profile-first wrapper for a compatible speech CLI")

    src = p.add_mutually_exclusive_group(required=True)
    src.add_argument("--text", help="Inline input text")
    src.add_argument("--text-file", help="Path to input text file")

    p.add_argument("--profile", help="Profile ID to use")
    p.add_argument("--profiles-file", help="JSON/YAML profiles file path")
    p.add_argument("--voice", choices=sorted(ALLOWED_VOICES))
    p.add_argument("--instructions", help="Override instructions text")
    p.add_argument("--speed", type=float)
    p.add_argument("--format", choices=sorted(ALLOWED_FORMATS), dest="format")
    p.add_argument("--model", help="Override model name")
    p.add_argument("--out", help="Output audio path")
    p.add_argument("--playback", choices=["none", "open", "afplay"], default=None, help="Playback backend for generated/queued audio")
    p.add_argument(
        "--autoplay",
        action=argparse.BooleanOptionalAction,
        default=None,
        help="Play generated audio immediately after synthesis",
    )
    p.add_argument("--queue-file", help="Newline-delimited list of audio files to play")
    p.add_argument("--repeat", type=int, default=1, help="Number of times to play each queued item")
    p.add_argument(
        "--stop-on-error",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Stop playback on first error (default true; pass --no-stop-on-error to continue)",
    )

    p.add_argument("--python-bin", default=sys.executable, help="Python interpreter for CLI invocation")
    p.add_argument(
        "--tts-cli-path",
        default="scripts/text_to_speech.py",
        help="Path to a compatible speech CLI (default expects scripts/text_to_speech.py)",
    )
    p.add_argument("--dry-run", action="store_true", help="Resolve and print command but skip execution")

    return p.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(sys.argv[1:] if argv is None else argv)

    try:
        if os.getenv("OPENAI_API_KEY") in (None, ""):
            raise WrapperError("OPENAI_API_KEY is required before running speech generation")

        runtime_config = load_runtime_config()
        effective_playback_backend = args.playback if args.playback is not None else runtime_config.local_playback_backend
        effective_autoplay = args.autoplay if args.autoplay is not None else runtime_config.local_autoplay_generated_audio

        text, input_source = _read_text(args)
        profile_set = resolve_profile_set(args, runtime_config)
        effective, profile_id, profile_source, disclosure = resolve_effective_config(args, profile_set, runtime_config)

        out_path = resolve_output_path(args, effective["response_format"], runtime_config)
        out_path.parent.mkdir(parents=True, exist_ok=True)

        tts_cli_path = Path(args.tts_cli_path)
        if not tts_cli_path.exists() and not args.dry_run:
            raise WrapperError(f"Bundled speech CLI not found: {tts_cli_path}")

        cmd = build_tts_command(args, text, effective, out_path)

        if args.dry_run:
            print("[DRY-RUN]", " ".join(cmd))
        else:
            subprocess.run(cmd, check=True)

        queue = resolve_playback_queue(args, out_path, effective_autoplay)
        playback = execute_playback(
            backend=effective_playback_backend,
            queue=queue,
            repeat=args.repeat,
            stop_on_error=args.stop_on_error,
            dry_run=args.dry_run,
        )

        manifest_payload = {
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "input_source": input_source,
            "profile_id": profile_id,
            "effective_voice": effective["voice"],
            "effective_instructions": effective["instructions"],
            "effective_speed": float(effective["speed"]),
            "summarize_mode": "none",
            "target_chars": None,
            "playback_backend": playback.backend,
            "playback_result": playback.result,
            "backend_mode": "local-cli",
            "disclosure": disclosure,
            "profile_source": profile_source,
            "playback_attempted": playback.attempted,
            "playback_succeeded": playback.succeeded,
            "playback_failed": playback.failed,
            "playback_errors": playback.errors,
            "playback_repeat": args.repeat,
            "playback_stop_on_error": args.stop_on_error,
            "playback_autoplay": effective_autoplay,
            "playback_queue_size": len(queue),
            "audio_output_path": str(out_path),
            "text_sha256": _sha256_text(text),
        }
        manifest_path = write_manifest(out_path, manifest_payload)

        print(f"[OK] Audio path: {out_path}")
        print(f"[OK] Manifest: {manifest_path}")
        if playback.exit_code != 0:
            print(f"[ERROR] Playback failed with deterministic exit code {playback.exit_code}", file=sys.stderr)
        return playback.exit_code
    except WrapperError as exc:
        print(f"[ERROR] {exc}", file=sys.stderr)
        return 2
    except subprocess.CalledProcessError as exc:
        print(f"[ERROR] Speech CLI failed with exit code {exc.returncode}", file=sys.stderr)
        return exc.returncode


if __name__ == "__main__":
    raise SystemExit(main())
